# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_mp3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditArtist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditArtist.setGeometry(QtCore.QRect(50, 100, 300, 30))
        self.lineEditArtist.setAutoFillBackground(False)
        self.lineEditArtist.setObjectName("lineEditArtist")
        self.lineEditAlbum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAlbum.setGeometry(QtCore.QRect(50, 150, 300, 30))
        self.lineEditAlbum.setObjectName("lineEditAlbum")
        self.lineEditYear = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditYear.setGeometry(QtCore.QRect(50, 200, 300, 30))
        self.lineEditYear.setObjectName("lineEditYear")
        self.lineEditUrl = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditUrl.setGeometry(QtCore.QRect(50, 50, 300, 30))
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.lineEditArtwork = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditArtwork.setGeometry(QtCore.QRect(50, 250, 300, 30))
        self.lineEditArtwork.setObjectName("lineEditArtwork")
        self.pushButtonDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDownload.setGeometry(QtCore.QRect(150, 300, 100, 30))
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.lineEditArtist.raise_()
        self.lineEditAlbum.raise_()
        self.lineEditYear.raise_()
        self.lineEditArtwork.raise_()
        self.pushButtonDownload.raise_()
        self.lineEditUrl.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditUrl, self.lineEditArtist)
        MainWindow.setTabOrder(self.lineEditArtist, self.lineEditAlbum)
        MainWindow.setTabOrder(self.lineEditAlbum, self.lineEditYear)
        MainWindow.setTabOrder(self.lineEditYear, self.lineEditArtwork)
        MainWindow.setTabOrder(self.lineEditArtwork, self.pushButtonDownload)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YouTube Download to MP3"))
        self.lineEditArtist.setPlaceholderText(_translate("MainWindow", "Enter Artist Name"))
        self.lineEditAlbum.setPlaceholderText(_translate("MainWindow", "Enter Album Name"))
        self.lineEditYear.setPlaceholderText(_translate("MainWindow", "Enter Album Year"))
        self.lineEditUrl.setPlaceholderText(_translate("MainWindow", "Enter Video or Playlist URL"))
        self.lineEditArtwork.setPlaceholderText(_translate("MainWindow", "(Optional) Enter Artwork URL"))
        self.pushButtonDownload.setText(_translate("MainWindow", "Download"))
        self.pushButtonDownload.setShortcut(_translate("MainWindow", "Ctrl+D"))
